TRAINING_SAMPLES = [
    ("starbucks coffee", "dining"),
    ("uber ride downtown", "transport"),
    ("monthly apartment rent", "rent"),
    ("electricity bill payment", "utilities"),
    ("walmart grocery shopping", "groceries"),
    ("whole foods market", "groceries"),
    ("spotify subscription", "entertainment"),
    ("netflix monthly plan", "entertainment"),
    ("movie theater tickets", "entertainment"),
    ("restaurant dinner", "dining"),
    ("chipotle lunch", "dining"),
    ("shell fuel gas", "transport"),
    ("train monthly pass", "transport"),
    ("doctor consultation", "healthcare"),
    ("pharmacy medicines", "healthcare"),
    ("dental clinic payment", "healthcare"),
    ("amazon online shopping", "shopping"),
    ("best buy electronics", "shopping"),
    ("clothing store purchase", "shopping"),
    ("flight booking", "travel"),
    ("hotel reservation", "travel"),
    ("vacation expenses", "travel"),
    ("internet broadband bill", "utilities"),
    ("water utility bill", "utilities"),
    ("mobile phone recharge", "utilities"),
    ("salary deposit", "salary"),
    ("freelance payment", "salary"),
    ("bonus payout", "salary"),
    ("tuition payment", "education"),
    ("online course fee", "education"),
    ("school supplies", "education"),
    ("gym membership", "healthcare"),
    ("grocery delivery", "groceries"),
    ("taxi fare", "transport"),
    ("concert tickets", "entertainment"),
    ("bookstore purchase", "education"),
    ("home rent transfer", "rent"),
    ("mortgage payment", "rent"),
    ("car insurance", "utilities"),
    ("maintenance service", "utilities"),
    ("weekend brunch", "dining"),
    ("bakery purchase", "dining"),
    ("department store", "shopping"),
    ("petrol station", "transport"),
    ("medical lab test", "healthcare"),
    ("airbnb stay", "travel"),
    ("coding bootcamp", "education"),
    ("market vegetables", "groceries"),
    ("home supplies", "shopping"),
    ("music streaming", "entertainment"),
]
