from app.schemas.assistant import (
    AdvisorQuery,
    AdvisorResponse,
    AssistantChatQuery,
    AssistantChatResponse,
    AssistantTaskCreate,
    AssistantTaskRead,
    AssistantTaskUpdate,
    DonationCreate,
    DonationRead,
    FeedbackCreate,
    FeedbackRead,
    UserPreferenceRead,
    UserPreferenceUpdate,
)
from app.schemas.analytics import AnalyticsSummaryResponse, HealthScoreResponse, SpendingForecastPoint
from app.schemas.automation import (
    AutomationInsightsResponse,
    GoalPlanRequest,
    GoalPlanResponse,
    LoanEmiRequest,
    LoanEmiResponse,
    RetirementPlanRequest,
    RetirementPlanResponse,
    SipProjectionRequest,
    SipProjectionResponse,
)
from app.schemas.budget import BudgetCreate, BudgetRead
from app.schemas.transaction import TransactionCreate, TransactionRead

__all__ = [
    "AdvisorQuery",
    "AdvisorResponse",
    "AssistantChatQuery",
    "AssistantChatResponse",
    "AssistantTaskCreate",
    "AssistantTaskRead",
    "AssistantTaskUpdate",
    "AnalyticsSummaryResponse",
    "AutomationInsightsResponse",
    "HealthScoreResponse",
    "SpendingForecastPoint",
    "BudgetCreate",
    "BudgetRead",
    "DonationCreate",
    "DonationRead",
    "FeedbackCreate",
    "FeedbackRead",
    "GoalPlanRequest",
    "GoalPlanResponse",
    "LoanEmiRequest",
    "LoanEmiResponse",
    "RetirementPlanRequest",
    "RetirementPlanResponse",
    "SipProjectionRequest",
    "SipProjectionResponse",
    "TransactionCreate",
    "TransactionRead",
    "UserPreferenceRead",
    "UserPreferenceUpdate",
]
